version: "3.9"


services:

    mysqldb:

        image: ${MYSQL_IMAGE}
        container_name: ${MYSQL_CONTAINER_NAME}


        restart: always


        env_file:

            - .env


        environment:

            MYSQL_DATABASE: ${MYSQL_DATABASE}

            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

            MYSQL_USER: ${MYSQL_USER}

            MYSQL_PASSWORD: ${MYSQL_PASSWORD}


            TZ: ${TZ}



        ports:

            - "${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}"



        volumes:

            # 数据持久化
            - "${MYSQL_DATA_PATH}:/var/lib/mysql"


            # 初始化SQL
            - "./init:/docker-entrypoint-initdb.d"



        command:

            --character-set-server=${MYSQL_CHARSET}
            --collation-server=${MYSQL_COLLATION}


        networks:

            - app-network



    redis:

        image: ${REDIS_IMAGE}
        container_name: ${REDIS_CONTAINER_NAME}


        restart: always


        env_file:

            - .env


        ports:

            - "${REDIS_PORT}:${REDIS_CONTAINER_PORT}"


        volumes:

            # 数据持久化
            - "${REDIS_DATA_PATH}:/data"



        command:

            redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes


        networks:

            - app-network



networks:

    app-network:

        driver: bridge